### ISSUE TITLE
Invoice resource in admin API

### ISSUE THREAD

**Issue by dmitry-sinina** [yeti-switch/yeti-web#1377]
resource should allow fetch invoice with all attributes + origination prefixes, origination networks, termination prefixes, termination networks data + odf and pdf files

**Comment by hcaldicott** [comment]
To provide some context on how this will be used, this API endpoint will be leveraged for this: https://blog.hostbillapp.com/2020/09/04/new-feature-diy-metered-billing/

I would like to be able to run an API call, as an admin, to Yeti-Switch containing the customer's account ID and a date range. This api call should return a summary of destination networks/prefixes, call counts, durations and amounts, just like the tables displayed in the invoice otherwise would, e.g.:

![image](https://github.com/yeti-switch/yeti-web/assets/1539430/c7f7b7cd-1c42-4deb-9e83-de81727e8662)

Each prefix/destination would ideally be it's own JSON object/collection containing the relevant fields within - call count, duration, amount, etc.
